[package]
name = "text-svg"
version = "0.1.1"
edition = "2021"
repository = "https://github.com/matthunz/text-svg"
description = "Render text or glyphs in a font to an SVG path"

[lib]
name = "text_svg"

[dependencies]
font-kit = "0.11.0"
rusttype = "0.9.3"
svg = "0.12.1"
