[package]
name = "font-svg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
font-kit = "0.11.0"
pathfinder_geometry = "0.5.1"
rusttype = "0.9.3"
svg = "0.12.1"
